#162 added description for option "Flush the cache at new comments"
pluginkollektiv/cachify pull request #179
Opened 2019-11-11 11:54 UTC by 00travelgirl00

closes #162

2019-11-23 17:34 UTC, bueltge requested changes

2019-11-23 17:34 UTC, bueltge commented on inc/cachify.settings.php
> +						<?php esc_html_e( '(Only works for comments which comes from the front-end, not added from the back-end)', 'cachify' ); ?>
The singular verb comes does not appear to agree the plural subject comments, I mean it should use come.

2019-11-23 17:35 UTC, bueltge commented on inc/cachify.settings.php
> +						<?php esc_html_e( '(Only works for comments which comes from the front-end, not added from the back-end)', 'cachify' ); ?>
Small mindset. Maybe we should also add a point after each sentence. However currently we it not always on the messages.

2019-11-24 17:32 UTC, derweili commented
As far as I can check this functionality, when adding comments from the frontend, backend or REST-API there is no difference in the "Clear Cache Behavior".

In both cases, if the checkbox is checked or not, the frontend and backend work the same for me.

2021-12-23 12:50 UTC, florianbrinkmann commented
I misunderstood the option when opening the issue that this PR is for, it indeed works like it should.

2021-12-23 12:50 UTC, closed without merging

2021-12-23 12:53 UTC, florianbrinkmann commented
PS: thanks for opening a PR to fix the issue, @00travelgirl00, and sorry for the work resulting from my misunderstanding.