Correction of small spelling mistakes
pluginkollektiv/cachify pull request #193
Opened 2020-04-18 15:51 UTC by timse201

2020-04-18 17:26 UTC, stklcode approved these changes

2020-04-18 17:32 UTC, krafit requested changes

2020-04-18 18:56 UTC, stklcode commented on inc/cachify.settings.php
> +						<?php esc_html_e( 'Browser User Agents', 'cachify' ); ?>
The linked article states "User-Agent" as header name, but "user agent" in the description text. Maybe not a mistake by definition, I'd prefer the one without hyphen though.

2020-04-19 01:42 UTC, timse201 commented on inc/cachify.settings.php
> +						<?php esc_html_e( 'Browser User Agents', 'cachify' ); ?>
user agent is not present in the Cambridge or Oxford dictionary so we have to use some other common dictionary's

https://www.wordreference.com/ende/user%20agent
global rank 584
https://www.similarweb.com/website/wordreference.com

https://en.wiktionary.org/wiki/user_agent
global rank 750
https://www.similarweb.com/website/wiktionary.org

https://encyclopedia2.thefreedictionary.com/User+agent
global rank 2318
https://www.similarweb.com/website/thefreedictionary.com

https://www.dict.cc/?s=user+agent
global rank 2722
https://www.similarweb.com/website/dict.cc

2020-05-25 15:58 UTC, merged