Update deprecated WPMS hooks
pluginkollektiv/cachify pull request #246
Opened 2021-11-16 17:07 UTC by ouun

`delete_blog` & `wpmu_new_blog` are deprecated since WP 5.1. This PR follows up.

References:
https://developer.wordpress.org/reference/hooks/wpmu_new_blog/
https://developer.wordpress.org/reference/hooks/delete_blog/

2021-11-16 18:29 UTC, stklcode requested changes
Hi @ouun, thanks for your PR.

The changes are absolutely reasonable. I left a minor remark in the argument types though.

2021-11-16 18:29 UTC, stklcode commented on inc/class-cachify.php
> +	public static function uninstall_later( $old_site ) {
The change for `install_later` add the type hint ` WP_Site $new_site`. Was this omitted in this place intentionally?

However, this is strictly speaking public API. So I'd suggest to make it backwards compatible for now, i.e. drop the type hint and use implicit union type `int|WP_Site`. We only need the ID anyway, so we can simply extract it, if we get a `WP_Site`  instance and passthrough integers.

2021-11-16 18:39 UTC, stklcode commented
Another decision that should at least be discussed briefly:

[`wp_initialize_site`](https://developer.wordpress.org/reference/functions/wp_initialize_site/) and [`wp_delete_site`](https://developer.wordpress.org/reference/functions/wp_delete_site/) have both been introduced in 5.1 - _Cachify_ currently declares compatibility with 4.4+

So we either drop support for WP <5.1 or add both hooks, maybe conditionally.

2022-01-07 12:34 UTC, florianbrinkmann commented
> So we either drop support for WP <5.1 or add both hooks, maybe conditionally.

I would vote for adding both and checking for the WordPress version.

2022-02-03 16:48 UTC, stklcode commented on inc/class-cachify.php
> +				add_action( 'wp_initialize_site', array( __CLASS__, 'install_later' ) );
Do we agree that [`wp_initialize_site`](https://developer.wordpress.org/reference/hooks/wp_initialize_site/) is the correct hook here?

We used to use [`wpmu_new_blog`](https://developer.wordpress.org/reference/hooks/wpmu_new_blog/) which "fires immediately after a new site is created".
The recommended replacement is [`wp_insert_site`](https://developer.wordpress.org/reference/hooks/wp_insert_site/) which "fires once a site has been inserted into the database".

We do add empty options (i.e. all default) into the database. Can be seen as part of the "initialization routine", so the initialize-hook might be the semantically better choice here. Just wanna make sure this is done intentionally.

2022-11-19 11:11 UTC, stklcode commented on inc/class-cachify.php
> +		switch_to_blog( is_int( $new_site ) ? $new_site : $new_site->blog_id );
Guess the argument should be `$old_site` here.

2022-11-19 11:20 UTC, stklcode approved these changes
Just fixed a small copy&paste bug and added some cosmetic changes to the PHPdocs.

I'm fine with the changes.

2022-11-20 09:40 UTC, merged