WIP: Inform user on cache clear in admin bar
pluginkollektiv/cachify pull request #257
Opened 2022-02-01 18:23 UTC by angelocali

In this pull request, a REST API endpoint is registered through which the cache can be flushed. The Flush site cache button in the admin bar executes a JavaScript function that makes an HTTP request to this endpoint. The user receives an indication whether the request was successful via color coding (currently green and red - possibly bad for color vision deficiency - should be reconsidered).

I would be very happy about feedback on this.

2022-02-02 08:13 UTC, florianbrinkmann commented on inc/class-cachify.php
> +				'href' => '',
I would keep the `href` so that it continues to work when the JS fails to load for some reason.

2022-02-02 08:13 UTC, bueltge requested changes
Thanks a lot for this PR, please look at my note to the exclusion of the styles.

2022-02-02 08:13 UTC, bueltge commented on inc/class-cachify.php
> +		echo '
In my opinion, we should exclude this style to a css file in the directory /css. After them, we have the possibility to use the API (`wp_register_style`) to include them, remove them, minified and pack them.

2022-02-02 09:04 UTC, bueltge approved these changes

2022-02-02 20:25 UTC, angelocali commented
@florianbrinkmann @bueltge Thank you very much. 

@florianbrinkmann and I worked together and changed the way the admin bar icon notifies the success or failure of the AJAX-request. We removed that the icon changes the color to green or red. The `dashboard-trash` icon is replaced by the `dashboard-yes-alt` or `dashboard-dismiss` icon instead, based on success/failure state. After 2s it reverts back to the trash icon.  Meanwhile it is not possible to fire another clear cache with the admin bar item.

Now the link works as before if e.g. JavaScript was disabled. We added that the dashicon is `dashboard-yes-alt` after a cache action, so that the user nevertheless gets informed.

At least I extracted the css and js into seperate files.

2022-02-02 20:38 UTC, bueltge commented
Great stuff @angelocali 
i would leave small notes:
* constant `REST_NAMESPACE_V1 ` is not clear for me as name for a constant - maybe without V1?
* I miss `wp_register_style` before enqueue, because that's necessary to work on the scripts outside the plugin, and we should leave them always open, especially in case of caching plugins or custom installations, their control scripts and styles.

2022-02-02 21:27 UTC, angelocali commented
@bueltge Nice to hear you like it. I renamed it to `REST_NAMESPACE`. I'm not quite sure if I understood you correctly with the `wp_register_style` part. Now I'm registering the styles and scripts in `init` first before enqueueing it. Can you second that you meant this?

2022-02-03 06:27 UTC, bueltge approved these changes

2022-02-03 06:44 UTC, bueltge commented
In case of the constant. A constant is global visible, usable and speak for himself. Outside this development, if I read the name REST_NAMESPACE - what is the task of this constant? So in my opinion it should have a name that describe his task. You store the version of the Cachify version for REST, maybe the name should go in this direction, like CACHIFY_REST_VERSION.

Short: Write code for humans 👩👨, not only for machines.
helpful: https://ahmedmahmoud-eltaher.medium.com/clean-code-best-practice-for-naming-part-1-f67ebe8c0894

2022-02-03 06:59 UTC, stklcode commented
> Outside this development, if I read the name REST_NAMESPACE - what is the task of this constant?

At least it’s bound to the class here, so typically called or imported as `Cachify::REST_NAMESPACE` which is as precise as I’d personally like to read.

Of course it might be even more specific like `Cachify::CACHIFY_REST_PREFIX_V1` or similar. (for `…_VERSION` I would expect values like `v1` or `1`)

----

The PHPdoc comment could be less generic though. It states “endpointS“ although it’s bound to only a single value. Meaningful along with the code, in standalone docs or IDE suggestions `REST_ROUTE_FLUSH` is omitted.

2022-02-03 08:21 UTC, florianbrinkmann commented
> At least it’s bound to the class here, so typically called or imported as Cachify::REST_NAMESPACE which is as precise as I’d personally like to read.

I second that.

2022-02-04 07:23 UTC, florianbrinkmann commented
We forgot to make the `aria-live` strings translatable, so marked it as draft

2022-02-04 11:02 UTC, bueltge approved these changes

2022-02-04 13:06 UTC, pfefferle commented
The flush-button looks like a link, so you should change the cursor, to be consistent.

2022-02-04 14:13 UTC, florianbrinkmann commented
@pfefferle done!

2022-02-04 14:16 UTC, pfefferle approved these changes
LGTM

2022-02-08 09:15 UTC, bueltge approved these changes

2022-02-08 11:10 UTC, florianbrinkmann commented
@angelocali and I just tested the PR with WP 4.4 to check if the REST functionality works there, and it does. The only problem was that the success dashicon we use was introduced with WP 5.2, so we added a fallback for older versions in the last commits. Would you re-review that again, @pfefferle and @bueltge? Thanks! 😇

2022-02-08 11:21 UTC, bueltge approved these changes

2022-02-08 12:31 UTC, pfefferle approved these changes
LGTM

2022-02-08 13:21 UTC, merged